import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Footer from "@/components/custom-ui/footer";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mobilnost.ba",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} h-[100dvh] bg-gradient-to-br from-green-500 to-violet-500`}
      >
        <div className="mx-auto flex h-full max-w-screen-xl flex-col px-5 py-8 md:px-8">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
