import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "../globals.css";
import Footer from "@/components/custom-ui/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mobilnost.ba",
  description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
  children: ReactNode;
}>;

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={`${inter.className} mx-auto flex min-h-screen flex-col`}>
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
