import { Oswald, Lora, Roboto } from "next/font/google";
import type { Metadata } from "next";
import { ReactNode } from "react";
import "../globals.css";

import Footer from "@/components/custom-ui/footer";
import Header from "@/components/custom-ui/header";

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
});
const inter = Lora({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-lora",
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Mobilnost.ba",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

type RootLayoutProps = Readonly<{
  children: ReactNode;
}>;

const RootLayout = ({ children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable} ${inter.variable} ${roboto.variable} bg-gray-100`}
      >
        <div className="flex min-h-screen flex-col">
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
